package com.axanthic.icaria.common.registry;

import com.axanthic.icaria.common.entity.*;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.block.entity.BlockEntityType;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

public class IcariaBlockEntityTypes {
	public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITY_TYPES = DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE, IcariaIdents.ID);

	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<IcariaChestBlockEntity>> CHEST = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("icaria_chest", () -> new BlockEntityType<>(IcariaChestBlockEntity::new, IcariaBlocks.CHEST.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CrystalBlockEntity>> CRYSTAL = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("crystal", () -> new BlockEntityType<>(CrystalBlockEntity::new, IcariaBlocks.CALCITE_CRYSTAL.get(), IcariaBlocks.HALITE_CRYSTAL.get(), IcariaBlocks.JASPER_CRYSTAL.get(), IcariaBlocks.ZIRCON_CRYSTAL.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ForgeBlockEntity>> FORGE = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("forge", () -> new BlockEntityType<>(ForgeBlockEntity::new, IcariaBlocks.FORGE.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ForgeRedirectorBlockEntity>> FORGE_REDIRECTOR = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("forge_redirector", () -> new BlockEntityType<>(ForgeRedirectorBlockEntity::new, IcariaBlocks.FORGE.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<GrinderBlockEntity>> GRINDER = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("grinder", () -> new BlockEntityType<>(GrinderBlockEntity::new, IcariaBlocks.GRINDER.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<GrinderRedirectorBlockEntity>> GRINDER_REDIRECTOR = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("grinder_redirector", () -> new BlockEntityType<>(GrinderRedirectorBlockEntity::new, IcariaBlocks.GRINDER.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<IcariaHangingSignBlockEntity>> HANGING_SIGN = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("icaria_hanging_sign", () -> new BlockEntityType<>(IcariaHangingSignBlockEntity::new, IcariaBlocks.CYPRESS_HANGING_SIGN.get(), IcariaBlocks.CYPRESS_WALL_HANGING_SIGN.get(), IcariaBlocks.DROUGHTROOT_HANGING_SIGN.get(), IcariaBlocks.DROUGHTROOT_WALL_HANGING_SIGN.get(), IcariaBlocks.FIR_HANGING_SIGN.get(), IcariaBlocks.FIR_WALL_HANGING_SIGN.get(), IcariaBlocks.LAUREL_HANGING_SIGN.get(), IcariaBlocks.LAUREL_WALL_HANGING_SIGN.get(), IcariaBlocks.OLIVE_HANGING_SIGN.get(), IcariaBlocks.OLIVE_WALL_HANGING_SIGN.get(), IcariaBlocks.PLANE_HANGING_SIGN.get(), IcariaBlocks.PLANE_WALL_HANGING_SIGN.get(), IcariaBlocks.POPULUS_HANGING_SIGN.get(), IcariaBlocks.POPULUS_WALL_HANGING_SIGN.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<KettleBlockEntity>> KETTLE = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("kettle", () -> new BlockEntityType<>(KettleBlockEntity::new, IcariaBlocks.KETTLE.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<KilnBlockEntity>> KILN = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("kiln", () -> new BlockEntityType<>(KilnBlockEntity::new, IcariaBlocks.KILN.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<KilnRedirectorBlockEntity>> KILN_REDIRECTOR = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("kiln_redirector", () -> new BlockEntityType<>(KilnRedirectorBlockEntity::new, IcariaBlocks.KILN.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<IcariaSignBlockEntity>> SIGN = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("icaria_sign", () -> new BlockEntityType<>(IcariaSignBlockEntity::new, IcariaBlocks.CYPRESS_SIGN.get(), IcariaBlocks.CYPRESS_WALL_SIGN.get(), IcariaBlocks.DROUGHTROOT_SIGN.get(), IcariaBlocks.DROUGHTROOT_WALL_SIGN.get(), IcariaBlocks.FIR_SIGN.get(), IcariaBlocks.FIR_WALL_SIGN.get(), IcariaBlocks.LAUREL_SIGN.get(), IcariaBlocks.LAUREL_WALL_SIGN.get(), IcariaBlocks.OLIVE_SIGN.get(), IcariaBlocks.OLIVE_WALL_SIGN.get(), IcariaBlocks.PLANE_SIGN.get(), IcariaBlocks.PLANE_WALL_SIGN.get(), IcariaBlocks.POPULUS_SIGN.get(), IcariaBlocks.POPULUS_WALL_SIGN.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<IcariaSkullBlockEntity>> SKULL = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("icaria_skull", () -> new BlockEntityType<>(IcariaSkullBlockEntity::new, IcariaBlocks.AETERNAE_SKULL.get(), IcariaBlocks.AETERNAE_WALL_SKULL.get(), IcariaBlocks.ARGAN_HOUND_SKULL.get(), IcariaBlocks.ARGAN_HOUND_WALL_SKULL.get(), IcariaBlocks.CAPELLA_SKULL.get(), IcariaBlocks.CAPELLA_WALL_SKULL.get(), IcariaBlocks.CATOBLEPAS_SKULL.get(), IcariaBlocks.CATOBLEPAS_WALL_SKULL.get(), IcariaBlocks.CERVER_SKULL.get(), IcariaBlocks.CERVER_WALL_SKULL.get(), IcariaBlocks.CROCOTTA_SKULL.get(), IcariaBlocks.CROCOTTA_WALL_SKULL.get(), IcariaBlocks.CYPRESS_FOREST_HAG_SKULL.get(), IcariaBlocks.CYPRESS_FOREST_HAG_WALL_SKULL.get(), IcariaBlocks.DROUGHTROOT_FOREST_HAG_SKULL.get(), IcariaBlocks.DROUGHTROOT_FOREST_HAG_WALL_SKULL.get(), IcariaBlocks.FIR_FOREST_HAG_SKULL.get(), IcariaBlocks.FIR_FOREST_HAG_WALL_SKULL.get(), IcariaBlocks.LAUREL_FOREST_HAG_SKULL.get(), IcariaBlocks.LAUREL_FOREST_HAG_WALL_SKULL.get(), IcariaBlocks.OLIVE_FOREST_HAG_SKULL.get(), IcariaBlocks.OLIVE_FOREST_HAG_WALL_SKULL.get(), IcariaBlocks.PLANE_FOREST_HAG_SKULL.get(), IcariaBlocks.PLANE_FOREST_HAG_WALL_SKULL.get(), IcariaBlocks.POPULUS_FOREST_HAG_SKULL.get(), IcariaBlocks.POPULUS_FOREST_HAG_WALL_SKULL.get(), IcariaBlocks.REVENANT_SKULL.get(), IcariaBlocks.REVENANT_WALL_SKULL.get(), IcariaBlocks.SOW_SKULL.get(), IcariaBlocks.SOW_WALL_SKULL.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<StorageVaseBlockEntity>> STORAGE_VASE = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("storage_vase", () -> new BlockEntityType<>(StorageVaseBlockEntity::new, IcariaBlocks.STORAGE_VASE.get(), IcariaBlocks.WHITE_STORAGE_VASE.get(), IcariaBlocks.LIGHT_GRAY_STORAGE_VASE.get(), IcariaBlocks.GRAY_STORAGE_VASE.get(), IcariaBlocks.BLACK_STORAGE_VASE.get(), IcariaBlocks.BROWN_STORAGE_VASE.get(), IcariaBlocks.RED_STORAGE_VASE.get(), IcariaBlocks.ORANGE_STORAGE_VASE.get(), IcariaBlocks.YELLOW_STORAGE_VASE.get(), IcariaBlocks.LIME_STORAGE_VASE.get(), IcariaBlocks.GREEN_STORAGE_VASE.get(), IcariaBlocks.CYAN_STORAGE_VASE.get(), IcariaBlocks.LIGHT_BLUE_STORAGE_VASE.get(), IcariaBlocks.BLUE_STORAGE_VASE.get(), IcariaBlocks.PURPLE_STORAGE_VASE.get(), IcariaBlocks.MAGENTA_STORAGE_VASE.get(), IcariaBlocks.PINK_STORAGE_VASE.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<IcariaSpawnerBlockEntity>> SPAWNER = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("icaria_spawner", () -> new BlockEntityType<>(IcariaSpawnerBlockEntity::new, IcariaBlocks.ARACHNE_SPAWNER.get(), IcariaBlocks.REVENANT_SPAWNER.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<IcariaTrappedChestBlockEntity>> TRAPPED_CHEST = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("icaria_trapped_chest", () -> new BlockEntityType<>(IcariaTrappedChestBlockEntity::new, IcariaBlocks.TRAPPED_CHEST.get()));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TroughBlockEntity>> TROUGH = IcariaBlockEntityTypes.BLOCK_ENTITY_TYPES.register("trough", () -> new BlockEntityType<>(TroughBlockEntity::new, IcariaBlocks.CYPRESS_TROUGH.get(), IcariaBlocks.DROUGHTROOT_TROUGH.get(), IcariaBlocks.FIR_TROUGH.get(), IcariaBlocks.LAUREL_TROUGH.get(), IcariaBlocks.OLIVE_TROUGH.get(), IcariaBlocks.PLANE_TROUGH.get(), IcariaBlocks.POPULUS_TROUGH.get()));
}
