package com.axanthic.icaria.common.registry;

import com.axanthic.icaria.mixin.FireBlockAccess;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.FireBlock;

public class IcariaFlammables {
	public static void flammableBlock(Block pBlock, int pEncouragement, int pFlammability) {
		FireBlock fireBlock = (FireBlock) Blocks.FIRE;
		((FireBlockAccess) fireBlock).accessableFlammable(pBlock, pEncouragement, pFlammability);
	}

	public static void setup() {
		flammableBlock(IcariaBlocks.ARACHNE_STRING_BLOCK.get(), 30, 60);
		flammableBlock(IcariaBlocks.SPELT_BALE_BLOCK.get(), 60, 20);
		flammableBlock(IcariaBlocks.VINE_REED_BLOCK.get(), 5, 20);
		flammableBlock(IcariaBlocks.VINE_SPROUT_BLOCK.get(), 5, 20);
		flammableBlock(IcariaBlocks.CYPRESS_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.FALLEN_CYPRESS_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.CYPRESS_TWIGS.get(), 30, 60);
		flammableBlock(IcariaBlocks.CYPRESS_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_CYPRESS_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.CYPRESS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_CYPRESS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DEAD_CYPRESS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DEAD_CYPRESS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.CYPRESS_PLANKS.get(), 5 ,20);
		flammableBlock(IcariaBlocks.CYPRESS_DECO.SLAB.get(), 5, 20);
		flammableBlock(IcariaBlocks.CYPRESS_DECO.STAIRS.get(), 5, 20);
		flammableBlock(IcariaBlocks.CYPRESS_DECO.FENCE.get(), 5, 20);
		flammableBlock(IcariaBlocks.CYPRESS_DECO.GATE.get(), 5, 20);
		flammableBlock(IcariaBlocks.DROUGHTROOT_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.FALLEN_DROUGHTROOT_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.DROUGHTROOT_TWIGS.get(), 30, 60);
		flammableBlock(IcariaBlocks.DROUGHTROOT_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DROUGHTROOT_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DROUGHTROOT_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DROUGHTROOT_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DEAD_DROUGHTROOT_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DEAD_DROUGHTROOT_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DROUGHTROOT_PLANKS.get(), 5 ,20);
		flammableBlock(IcariaBlocks.DROUGHTROOT_DECO.SLAB.get(), 5, 20);
		flammableBlock(IcariaBlocks.DROUGHTROOT_DECO.STAIRS.get(), 5, 20);
		flammableBlock(IcariaBlocks.DROUGHTROOT_DECO.FENCE.get(), 5, 20);
		flammableBlock(IcariaBlocks.DROUGHTROOT_DECO.GATE.get(), 5, 20);
		flammableBlock(IcariaBlocks.FIR_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.FALLEN_FIR_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.FIR_TWIGS.get(), 30, 60);
		flammableBlock(IcariaBlocks.FIR_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_FIR_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.FIR_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_FIR_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DEAD_FIR_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DEAD_FIR_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.FIR_PLANKS.get(), 5 ,20);
		flammableBlock(IcariaBlocks.FIR_DECO.SLAB.get(), 5, 20);
		flammableBlock(IcariaBlocks.FIR_DECO.STAIRS.get(), 5, 20);
		flammableBlock(IcariaBlocks.FIR_DECO.FENCE.get(), 5, 20);
		flammableBlock(IcariaBlocks.FIR_DECO.GATE.get(), 5, 20);
		flammableBlock(IcariaBlocks.LAUREL_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.FALLEN_LAUREL_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.LAUREL_TWIGS.get(), 30, 60);
		flammableBlock(IcariaBlocks.LAUREL_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_LAUREL_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.LAUREL_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_LAUREL_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DEAD_LAUREL_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DEAD_LAUREL_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.LAUREL_PLANKS.get(), 5 ,20);
		flammableBlock(IcariaBlocks.LAUREL_DECO.SLAB.get(), 5, 20);
		flammableBlock(IcariaBlocks.LAUREL_DECO.STAIRS.get(), 5, 20);
		flammableBlock(IcariaBlocks.LAUREL_DECO.FENCE.get(), 5, 20);
		flammableBlock(IcariaBlocks.LAUREL_DECO.GATE.get(), 5, 20);
		flammableBlock(IcariaBlocks.OLIVE_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.OLIVE_LEAVES_BLACK.get(), 30, 60);
		flammableBlock(IcariaBlocks.OLIVE_LEAVES_GREEN.get(), 30, 60);
		flammableBlock(IcariaBlocks.FALLEN_OLIVE_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.OLIVE_TWIGS.get(), 30, 60);
		flammableBlock(IcariaBlocks.OLIVE_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_OLIVE_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.OLIVE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_OLIVE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DEAD_OLIVE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DEAD_OLIVE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.OLIVE_PLANKS.get(), 5 ,20);
		flammableBlock(IcariaBlocks.OLIVE_DECO.SLAB.get(), 5, 20);
		flammableBlock(IcariaBlocks.OLIVE_DECO.STAIRS.get(), 5, 20);
		flammableBlock(IcariaBlocks.OLIVE_DECO.FENCE.get(), 5, 20);
		flammableBlock(IcariaBlocks.OLIVE_DECO.GATE.get(), 5, 20);
		flammableBlock(IcariaBlocks.PLANE_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.FALLEN_PLANE_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.PLANE_TWIGS.get(), 30, 60);
		flammableBlock(IcariaBlocks.PLANE_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_PLANE_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.PLANE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_PLANE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DEAD_PLANE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DEAD_PLANE_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.PLANE_PLANKS.get(), 5 ,20);
		flammableBlock(IcariaBlocks.PLANE_DECO.SLAB.get(), 5, 20);
		flammableBlock(IcariaBlocks.PLANE_DECO.STAIRS.get(), 5, 20);
		flammableBlock(IcariaBlocks.PLANE_DECO.FENCE.get(), 5, 20);
		flammableBlock(IcariaBlocks.PLANE_DECO.GATE.get(), 5, 20);
		flammableBlock(IcariaBlocks.POPULUS_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.FALLEN_POPULUS_LEAVES.get(), 30, 60);
		flammableBlock(IcariaBlocks.POPULUS_TWIGS.get(), 30, 60);
		flammableBlock(IcariaBlocks.POPULUS_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_POPULUS_WOOD.get(), 5 ,5);
		flammableBlock(IcariaBlocks.POPULUS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_POPULUS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.DEAD_POPULUS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.STRIPPED_DEAD_POPULUS_LOG.get(), 5 ,5);
		flammableBlock(IcariaBlocks.POPULUS_PLANKS.get(), 5 ,20);
		flammableBlock(IcariaBlocks.POPULUS_DECO.SLAB.get(), 5, 20);
		flammableBlock(IcariaBlocks.POPULUS_DECO.STAIRS.get(), 5, 20);
		flammableBlock(IcariaBlocks.POPULUS_DECO.FENCE.get(), 5, 20);
		flammableBlock(IcariaBlocks.POPULUS_DECO.GATE.get(), 5, 20);
		flammableBlock(IcariaBlocks.FERN.get(), 60, 100);
		flammableBlock(IcariaBlocks.SMALL_GRASS.get(), 60, 100);
		flammableBlock(IcariaBlocks.MEDIUM_GRASS.get(), 60, 100);
		flammableBlock(IcariaBlocks.LARGE_GRASS.get(), 60, 100);
		flammableBlock(IcariaBlocks.GRAIN_0.get(), 60, 100);
		flammableBlock(IcariaBlocks.GRAIN_1.get(), 60, 100);
		flammableBlock(IcariaBlocks.GRAIN_2.get(), 60, 100);
		flammableBlock(IcariaBlocks.GRAIN_3.get(), 60, 100);
		flammableBlock(IcariaBlocks.GRAIN_4.get(), 60, 100);
		flammableBlock(IcariaBlocks.GRAIN_5.get(), 60, 100);
		flammableBlock(IcariaBlocks.BLINDWEED.get(), 60, 100);
		flammableBlock(IcariaBlocks.CHAMEOMILE.get(), 60, 100);
		flammableBlock(IcariaBlocks.CHARMONDER.get(), 60, 100);
		flammableBlock(IcariaBlocks.CLOVER.get(), 60, 100);
		flammableBlock(IcariaBlocks.FIREHILT.get(), 60, 100);
		flammableBlock(IcariaBlocks.BLUE_HYDRACINTH.get(), 60, 100);
		flammableBlock(IcariaBlocks.PURPLE_HYDRACINTH.get(), 60, 100);
		flammableBlock(IcariaBlocks.LIONFANGS.get(), 60, 100);
		flammableBlock(IcariaBlocks.SPEARDROPS.get(), 60, 100);
		flammableBlock(IcariaBlocks.PURPLE_STAGHORN.get(), 60, 100);
		flammableBlock(IcariaBlocks.YELLOW_STAGHORN.get(), 60, 100);
		flammableBlock(IcariaBlocks.BLUE_STORMCOTTON.get(), 60, 100);
		flammableBlock(IcariaBlocks.PINK_STORMCOTTON.get(), 60, 100);
		flammableBlock(IcariaBlocks.PURPLE_STORMCOTTON.get(), 60, 100);
		flammableBlock(IcariaBlocks.SUNKETTLE.get(), 60, 100);
		flammableBlock(IcariaBlocks.SUNSPONGE.get(), 60, 100);
		flammableBlock(IcariaBlocks.VOIDLILY.get(), 60, 100);
		flammableBlock(IcariaBlocks.BOLBOS.get(), 60, 100);
		flammableBlock(IcariaBlocks.DATHULLA.get(), 60, 100);
		flammableBlock(IcariaBlocks.MONDANOS.get(), 60, 100);
		flammableBlock(IcariaBlocks.MOTH_AGARIC.get(), 60, 100);
		flammableBlock(IcariaBlocks.NAMDRAKE.get(), 60, 100);
		flammableBlock(IcariaBlocks.PSILOCYBOS.get(), 60, 100);
		flammableBlock(IcariaBlocks.ROWAN.get(), 60, 100);
		flammableBlock(IcariaBlocks.BLUE_GROUND_FLOWERS.get(), 60, 100);
		flammableBlock(IcariaBlocks.CYAN_GROUND_FLOWERS.get(), 60, 100);
		flammableBlock(IcariaBlocks.PINK_GROUND_FLOWERS.get(), 60, 100);
		flammableBlock(IcariaBlocks.PURPLE_GROUND_FLOWERS.get(), 60, 100);
		flammableBlock(IcariaBlocks.RED_GROUND_FLOWERS.get(), 60, 100);
		flammableBlock(IcariaBlocks.WHITE_GROUND_FLOWERS.get(), 60, 100);
		flammableBlock(IcariaBlocks.PALM_FERN.get(), 60, 100);
		flammableBlock(IcariaBlocks.WHITE_BROMELIA.get(), 60, 100);
		flammableBlock(IcariaBlocks.ORANGE_BROMELIA.get(), 60, 100);
		flammableBlock(IcariaBlocks.PINK_BROMELIA.get(), 60, 100);
		flammableBlock(IcariaBlocks.PURPLE_BROMELIA.get(), 60, 100);
		flammableBlock(IcariaBlocks.STRAWBERRY_BUSH.get(), 60, 100);
	}
}
