package com.axanthic.icaria.common.registry;

import com.axanthic.icaria.common.entity.*;

import net.minecraft.MethodsReturnNonnullByDefault;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;

import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

import javax.annotation.ParametersAreNonnullByDefault;

@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

public class IcariaEntityTypes {
	public static final DeferredRegister<EntityType<?>> ENTITY_TYPES = DeferredRegister.create(Registries.ENTITY_TYPE, IcariaIdents.ID);

	public static final Supplier<EntityType<AeternaeEntity>> AETERNAE = IcariaEntityTypes.ENTITY_TYPES.register("aeternae", () -> EntityType.Builder.of(AeternaeEntity::new, MobCategory.CREATURE).sized(1.249F, 1.49F).eyeHeight(1.48F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ArachneEntity>> ARACHNE = IcariaEntityTypes.ENTITY_TYPES.register("arachne", () -> EntityType.Builder.of(ArachneEntity::new, MobCategory.MONSTER).sized(1.49F, 1.99F).eyeHeight(1.98F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ArachneDroneEntity>> ARACHNE_DRONE = IcariaEntityTypes.ENTITY_TYPES.register("arachne_drone", () -> EntityType.Builder.of(ArachneDroneEntity::new, MobCategory.MONSTER).sized(0.749F, 0.49F).eyeHeight(0.48F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ArganHoundEntity>> ARGAN_HOUND = IcariaEntityTypes.ENTITY_TYPES.register("argan_hound", () -> EntityType.Builder.of(ArganHoundEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.749F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<IcariaBarrelEntity>> BARREL = IcariaEntityTypes.ENTITY_TYPES.register("barrel", () -> EntityType.Builder.<IcariaBarrelEntity>of(IcariaBarrelEntity::new, MobCategory.MISC).sized(0.99F, 0.99F).clientTrackingRange(10).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<BidentEntity>> BIDENT = IcariaEntityTypes.ENTITY_TYPES.register("bident", () -> EntityType.Builder.<BidentEntity>of(BidentEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<CapellaEntity>> CAPELLA = IcariaEntityTypes.ENTITY_TYPES.register("capella", () -> EntityType.Builder.of(CapellaEntity::new, MobCategory.CREATURE).sized(1.249F, 1.49F).eyeHeight(0.99F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<CatoblepasEntity>> CATOBLEPAS = IcariaEntityTypes.ENTITY_TYPES.register("catoblepas", () -> EntityType.Builder.of(CatoblepasEntity::new, MobCategory.CREATURE).sized(1.249F, 1.249F).eyeHeight(1.248F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<CerverEntity>> CERVER = IcariaEntityTypes.ENTITY_TYPES.register("cerver", () -> EntityType.Builder.of(CerverEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.749F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<CrocottaEntity>> CROCOTTA = IcariaEntityTypes.ENTITY_TYPES.register("crocotta", () -> EntityType.Builder.of(CrocottaEntity::new, MobCategory.MONSTER).sized(0.99F, 1.249F).eyeHeight(0.99F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<FloatingBlockEntity>> FLOATING_BLOCK = IcariaEntityTypes.ENTITY_TYPES.register("floating_block", () -> EntityType.Builder.<FloatingBlockEntity>of(FloatingBlockEntity::new, MobCategory.MISC).sized(0.99F, 0.99F).clientTrackingRange(10).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<GreekFireGrenadeEntity>> GREEK_FIRE_GRENADE = IcariaEntityTypes.ENTITY_TYPES.register("greek_fire_grenade", () -> EntityType.Builder.<GreekFireGrenadeEntity>of(GreekFireGrenadeEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ForestHagEntity>> CYPRESS_FOREST_HAG = IcariaEntityTypes.ENTITY_TYPES.register("cypress_forest_hag", () -> EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.749F).eyeHeight(2.3749F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ForestHagEntity>> DROUGHTROOT_FOREST_HAG = IcariaEntityTypes.ENTITY_TYPES.register("droughtroot_forest_hag", () -> EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ForestHagEntity>> FIR_FOREST_HAG = IcariaEntityTypes.ENTITY_TYPES.register("fir_forest_hag", () -> EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ForestHagEntity>> LAUREL_FOREST_HAG = IcariaEntityTypes.ENTITY_TYPES.register("laurel_forest_hag", () -> EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ForestHagEntity>> OLIVE_FOREST_HAG = IcariaEntityTypes.ENTITY_TYPES.register("olive_forest_hag", () -> EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.12749F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ForestHagEntity>> PLANE_FOREST_HAG = IcariaEntityTypes.ENTITY_TYPES.register("plane_forest_hag", () -> EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.12749F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<ForestHagEntity>> POPULUS_FOREST_HAG = IcariaEntityTypes.ENTITY_TYPES.register("populus_forest_hag", () -> EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.12749F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<HyliasterEntity>> HYLIASTER = IcariaEntityTypes.ENTITY_TYPES.register("hyliaster", () -> EntityType.Builder.of(HyliasterEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.49F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<JellyfishEntity>> ENDER_JELLYFISH = IcariaEntityTypes.ENTITY_TYPES.register("ender_jellyfish", () -> EntityType.Builder.of(JellyfishEntity::new, MobCategory.AMBIENT).sized(0.749F, 0.749F).eyeHeight(0.49F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<JellyfishEntity>> FIRE_JELLYFISH = IcariaEntityTypes.ENTITY_TYPES.register("fire_jellyfish", () -> EntityType.Builder.of(JellyfishEntity::new, MobCategory.AMBIENT).fireImmune().sized(0.749F, 0.749F).eyeHeight(0.49F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<JellyfishEntity>> NATURE_JELLYFISH = IcariaEntityTypes.ENTITY_TYPES.register("nature_jellyfish", () -> EntityType.Builder.of(JellyfishEntity::new, MobCategory.AMBIENT).sized(0.749F, 0.749F).eyeHeight(0.49F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<JellyfishEntity>> VOID_JELLYFISH = IcariaEntityTypes.ENTITY_TYPES.register("void_jellyfish", () -> EntityType.Builder.of(JellyfishEntity::new, MobCategory.AMBIENT).sized(0.749F, 0.749F).eyeHeight(0.49F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<JellyfishEntity>> WATER_JELLYFISH = IcariaEntityTypes.ENTITY_TYPES.register("water_jellyfish", () -> EntityType.Builder.of(JellyfishEntity::new, MobCategory.AMBIENT).sized(0.749F, 0.749F).eyeHeight(0.49F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<LootVaseEntity>> LOOT_VASE = IcariaEntityTypes.ENTITY_TYPES.register("loot_vase", () -> EntityType.Builder.<LootVaseEntity>of(LootVaseEntity::new, MobCategory.MISC).sized(0.99F, 0.99F).clientTrackingRange(10).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<MyrmekeDroneEntity>> MYRMEKE_DRONE = IcariaEntityTypes.ENTITY_TYPES.register("myrmeke_drone", () -> EntityType.Builder.of(MyrmekeDroneEntity::new, MobCategory.MONSTER).sized(0.749F, 0.49F).eyeHeight(0.249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<MyrmekeSoldierEntity>> MYRMEKE_SOLDIER = IcariaEntityTypes.ENTITY_TYPES.register("myrmeke_soldier", () -> EntityType.Builder.of(MyrmekeSoldierEntity::new, MobCategory.MONSTER).sized(0.749F, 0.49F).eyeHeight(0.249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<MyrmekeQueenEntity>> MYRMEKE_QUEEN = IcariaEntityTypes.ENTITY_TYPES.register("myrmeke_queen", () -> EntityType.Builder.of(MyrmekeQueenEntity::new, MobCategory.MONSTER).sized(0.99F, 0.49F).eyeHeight(0.249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<IcariaPaintingEntity>> PAINTING = IcariaEntityTypes.ENTITY_TYPES.register("painting", () -> EntityType.Builder.<IcariaPaintingEntity>of(IcariaPaintingEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(10).updateInterval(Integer.MAX_VALUE).build(IcariaIdents.ID));
	public static final Supplier<EntityType<CaptainRevenantEntity>> CAPTAIN_REVENANT = IcariaEntityTypes.ENTITY_TYPES.register("captain_revenant", () -> EntityType.Builder.of(CaptainRevenantEntity::new, MobCategory.MONSTER).sized(0.749F, 1.99F).eyeHeight(1.749F).fireImmune().build(IcariaIdents.ID));
	public static final Supplier<EntityType<CivilianRevenantEntity>> CIVILIAN_REVENANT = IcariaEntityTypes.ENTITY_TYPES.register("civilian_revenant", () -> EntityType.Builder.of(CivilianRevenantEntity::new, MobCategory.MONSTER).sized(0.749F, 1.99F).eyeHeight(1.749F).fireImmune().build(IcariaIdents.ID));
	public static final Supplier<EntityType<CrawlerRevenantEntity>> CRAWLER_REVENANT = IcariaEntityTypes.ENTITY_TYPES.register("crawler_revenant", () -> EntityType.Builder.of(CrawlerRevenantEntity::new, MobCategory.MONSTER).sized(0.749F, 0.749F).eyeHeight(0.3749F).fireImmune().build(IcariaIdents.ID));
	public static final Supplier<EntityType<OvergrownRevenantEntity>> OVERGROWN_REVENANT = IcariaEntityTypes.ENTITY_TYPES.register("overgrown_revenant", () -> EntityType.Builder.of(OvergrownRevenantEntity::new, MobCategory.MONSTER).sized(0.749F, 1.99F).eyeHeight(1.749F).fireImmune().build(IcariaIdents.ID));
	public static final Supplier<EntityType<PyromancerRevenantEntity>> PYROMANCER_REVENANT = IcariaEntityTypes.ENTITY_TYPES.register("pyromancer_revenant", () -> EntityType.Builder.of(PyromancerRevenantEntity::new, MobCategory.MONSTER).sized(0.749F, 1.99F).eyeHeight(1.749F).fireImmune().build(IcariaIdents.ID));
	public static final Supplier<EntityType<NetherPyromancerRevenantEntity>> NETHER_PYROMANCER_REVENANT = IcariaEntityTypes.ENTITY_TYPES.register("nether_pyromancer_revenant", () -> EntityType.Builder.of(NetherPyromancerRevenantEntity::new, MobCategory.MONSTER).sized(0.749F, 1.99F).eyeHeight(1.749F).fireImmune().build(IcariaIdents.ID));
	public static final Supplier<EntityType<SoldierRevenantEntity>> SOLDIER_REVENANT = IcariaEntityTypes.ENTITY_TYPES.register("soldier_revenant", () -> EntityType.Builder.of(SoldierRevenantEntity::new, MobCategory.MONSTER).sized(0.749F, 1.99F).eyeHeight(1.749F).fireImmune().build(IcariaIdents.ID));
	public static final Supplier<EntityType<ScorpionEntity>> SCORPION = IcariaEntityTypes.ENTITY_TYPES.register("scorpion", () -> EntityType.Builder.of(ScorpionEntity::new, MobCategory.MONSTER).sized(1.49F, 0.99F).eyeHeight(0.6249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<SlugEntity>> CRYSTAL_SLUG = IcariaEntityTypes.ENTITY_TYPES.register("crystal_slug", () -> EntityType.Builder.of(SlugEntity::new, MobCategory.MONSTER).sized(1.249F, 0.749F).eyeHeight(0.748F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<SnullEntity>> FOREST_SNULL = IcariaEntityTypes.ENTITY_TYPES.register("forest_snull", () -> EntityType.Builder.of(SnullEntity::new, MobCategory.MONSTER).sized(0.749F, 0.749F).eyeHeight(0.6249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<SnullEntity>> SNULL = IcariaEntityTypes.ENTITY_TYPES.register("snull", () -> EntityType.Builder.of(SnullEntity::new, MobCategory.MONSTER).sized(0.749F, 0.749F).eyeHeight(0.6249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<SolifugaeEntity>> SOLIFUGAE = IcariaEntityTypes.ENTITY_TYPES.register("solifugae", () -> EntityType.Builder.of(SolifugaeEntity::new, MobCategory.MONSTER).sized(0.99F, 0.49F).eyeHeight(0.48F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<SowEntity>> SOW = IcariaEntityTypes.ENTITY_TYPES.register("sow", () -> EntityType.Builder.of(SowEntity::new, MobCategory.CREATURE).sized(0.749F, 0.749F).eyeHeight(0.6249F).build(IcariaIdents.ID));
	public static final Supplier<EntityType<AntiGravitySpellEntity>> ANTI_GRAVITY_SPELL = IcariaEntityTypes.ENTITY_TYPES.register("anti_gravity_spell", () -> EntityType.Builder.of(AntiGravitySpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<FortifyingSpellEntity>> FORTIFYING_SPELL = IcariaEntityTypes.ENTITY_TYPES.register("fortifying_spell", () -> EntityType.Builder.of(FortifyingSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<HealingSpellEntity>> HEALING_SPELL = IcariaEntityTypes.ENTITY_TYPES.register("healing_spell", () -> EntityType.Builder.of(HealingSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<BubbleSpellEntity>> BUBBLE_SPELL = IcariaEntityTypes.ENTITY_TYPES.register("bubble_spell", () -> EntityType.Builder.of(BubbleSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<FreezingSpellEntity>> FREEZING_SPELL = IcariaEntityTypes.ENTITY_TYPES.register("freezing_spell", () -> EntityType.Builder.of(FreezingSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<MagicMissileSpellEntity>> MAGIC_MISSILE_SPELL = IcariaEntityTypes.ENTITY_TYPES.register("magic_missile_spell", () -> EntityType.Builder.of(MagicMissileSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<VinegarEntity>> VINEGAR = IcariaEntityTypes.ENTITY_TYPES.register("vinegar", () -> EntityType.Builder.<VinegarEntity>of(VinegarEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).build(IcariaIdents.ID));
	public static final Supplier<EntityType<VinegaroonEntity>> VINEGAROON = IcariaEntityTypes.ENTITY_TYPES.register("vinegaroon", () -> EntityType.Builder.of(VinegaroonEntity::new, MobCategory.MONSTER).sized(1.49F, 0.749F).eyeHeight(0.748F).build(IcariaIdents.ID));
}
