package com.axanthic.icaria.common.registry;

import com.axanthic.icaria.annotation.MethodsReturnNonnullByDefault;
import com.axanthic.icaria.annotation.ParametersAreNonnullByDefault;
import com.axanthic.icaria.common.entity.*;
import com.axanthic.icaria.common.ids.IcariaEntityTypeIds;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

public class IcariaEntityTypes {
	public static final DeferredRegister<EntityType<?>> ENTITY_TYPES = DeferredRegister.create(Registries.ENTITY_TYPE, IcariaIds.ID);

	public static final DeferredHolder<EntityType<?>, EntityType<AeternaeEntity>> AETERNAE = IcariaEntityTypes.register(IcariaEntityTypeIds.AETERNAE, EntityType.Builder.of(AeternaeEntity::new, MobCategory.CREATURE).sized(0.99F, 1.49F).eyeHeight(1.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<ArachneEntity>> ARACHNE = IcariaEntityTypes.register(IcariaEntityTypeIds.ARACHNE, EntityType.Builder.of(ArachneEntity::new, MobCategory.MONSTER).sized(1.49F, 1.99F).eyeHeight(1.99F));
	public static final DeferredHolder<EntityType<?>, EntityType<ArachneDroneEntity>> ARACHNE_DRONE = IcariaEntityTypes.register(IcariaEntityTypeIds.ARACHNE_DRONE, EntityType.Builder.of(ArachneDroneEntity::new, MobCategory.MONSTER).sized(0.99F, 0.749F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<ArganHoundEntity>> ARGAN_HOUND = IcariaEntityTypes.register(IcariaEntityTypeIds.ARGAN_HOUND, EntityType.Builder.of(ArganHoundEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.749F));
	public static final DeferredHolder<EntityType<?>, EntityType<IcariaBarrelEntity>> BARREL = IcariaEntityTypes.register(IcariaEntityTypeIds.BARREL, EntityType.Builder.<IcariaBarrelEntity>of(IcariaBarrelEntity::new, MobCategory.MISC).sized(0.99F, 0.99F).clientTrackingRange(10).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<BidentEntity>> BIDENT = IcariaEntityTypes.register(IcariaEntityTypeIds.BIDENT, EntityType.Builder.<BidentEntity>of(BidentEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<CapellaEntity>> CAPELLA = IcariaEntityTypes.register(IcariaEntityTypeIds.CAPELLA, EntityType.Builder.of(CapellaEntity::new, MobCategory.CREATURE).sized(0.749F, 0.99F).eyeHeight(0.749F));
	public static final DeferredHolder<EntityType<?>, EntityType<CatoblepasEntity>> CATOBLEPAS = IcariaEntityTypes.register(IcariaEntityTypeIds.CATOBLEPAS, EntityType.Builder.of(CatoblepasEntity::new, MobCategory.CREATURE).sized(0.99F, 1.249F).eyeHeight(1.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<CerverEntity>> CERVER = IcariaEntityTypes.register(IcariaEntityTypeIds.CERVER, EntityType.Builder.of(CerverEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.749F));
	public static final DeferredHolder<EntityType<?>, EntityType<CrocottaEntity>> CROCOTTA = IcariaEntityTypes.register(IcariaEntityTypeIds.CROCOTTA, EntityType.Builder.of(CrocottaEntity::new, MobCategory.MONSTER).sized(0.99F, 1.249F).eyeHeight(0.99F));
	public static final DeferredHolder<EntityType<?>, EntityType<FeeshEntity>> FEESH = IcariaEntityTypes.register(IcariaEntityTypeIds.FEESH, EntityType.Builder.of(FeeshEntity::new, MobCategory.WATER_AMBIENT).sized(0.49F, 0.49F).eyeHeight(0.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<FicheEntity>> FICHE = IcariaEntityTypes.register(IcariaEntityTypeIds.FICHE, EntityType.Builder.of(FicheEntity::new, MobCategory.WATER_AMBIENT).sized(0.49F, 0.49F).eyeHeight(0.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<FisshhEntity>> FISSHH = IcariaEntityTypes.register(IcariaEntityTypeIds.FISSHH, EntityType.Builder.of(FisshhEntity::new, MobCategory.WATER_AMBIENT).sized(0.49F, 0.49F).eyeHeight(0.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<FyshEntity>> FYSH = IcariaEntityTypes.register(IcariaEntityTypeIds.FYSH, EntityType.Builder.of(FyshEntity::new, MobCategory.WATER_AMBIENT).sized(0.49F, 0.49F).eyeHeight(0.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<FloatingBlockEntity>> FLOATING_BLOCK = IcariaEntityTypes.register(IcariaEntityTypeIds.FLOATING_BLOCK, EntityType.Builder.<FloatingBlockEntity>of(FloatingBlockEntity::new, MobCategory.MISC).sized(0.99F, 0.99F).clientTrackingRange(10).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<ForestHagEntity>> CYPRESS_FOREST_HAG = IcariaEntityTypes.register(IcariaEntityTypeIds.CYPRESS_FOREST_HAG, EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.749F).eyeHeight(2.3749F));
	public static final DeferredHolder<EntityType<?>, EntityType<ForestHagEntity>> DROUGHTROOT_FOREST_HAG = IcariaEntityTypes.register(IcariaEntityTypeIds.DROUGHTROOT_FOREST_HAG, EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F));
	public static final DeferredHolder<EntityType<?>, EntityType<ForestHagEntity>> FIR_FOREST_HAG = IcariaEntityTypes.register(IcariaEntityTypeIds.FIR_FOREST_HAG, EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F));
	public static final DeferredHolder<EntityType<?>, EntityType<ForestHagEntity>> LAUREL_FOREST_HAG = IcariaEntityTypes.register(IcariaEntityTypeIds.LAUREL_FOREST_HAG, EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F));
	public static final DeferredHolder<EntityType<?>, EntityType<ForestHagEntity>> OLIVE_FOREST_HAG = IcariaEntityTypes.register(IcariaEntityTypeIds.OLIVE_FOREST_HAG, EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F));
	public static final DeferredHolder<EntityType<?>, EntityType<ForestHagEntity>> PLANE_FOREST_HAG = IcariaEntityTypes.register(IcariaEntityTypeIds.PLANE_FOREST_HAG, EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F));
	public static final DeferredHolder<EntityType<?>, EntityType<ForestHagEntity>> POPULUS_FOREST_HAG = IcariaEntityTypes.register(IcariaEntityTypeIds.POPULUS_FOREST_HAG, EntityType.Builder.of(ForestHagEntity::new, MobCategory.MONSTER).sized(0.99F, 2.49F).eyeHeight(2.1249F));
	public static final DeferredHolder<EntityType<?>, EntityType<GreekFireGrenadeEntity>> GREEK_FIRE_GRENADE = IcariaEntityTypes.register(IcariaEntityTypeIds.GREEK_FIRE_GRENADE, EntityType.Builder.<GreekFireGrenadeEntity>of(GreekFireGrenadeEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<HyliasterEntity>> HYLIASTER = IcariaEntityTypes.register(IcariaEntityTypeIds.HYLIASTER, EntityType.Builder.of(HyliasterEntity::new, MobCategory.MONSTER).sized(0.749F, 0.749F).eyeHeight(0.3749F));
	public static final DeferredHolder<EntityType<?>, EntityType<EnderJellyfishEntity>> ENDER_JELLYFISH = IcariaEntityTypes.register(IcariaEntityTypeIds.ENDER_JELLYFISH, EntityType.Builder.of(EnderJellyfishEntity::new, MobCategory.WATER_AMBIENT).sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<FireJellyfishEntity>> FIRE_JELLYFISH = IcariaEntityTypes.register(IcariaEntityTypeIds.FIRE_JELLYFISH, EntityType.Builder.of(FireJellyfishEntity::new, MobCategory.WATER_AMBIENT).fireImmune().sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<NatureJellyfishEntity>> NATURE_JELLYFISH = IcariaEntityTypes.register(IcariaEntityTypeIds.NATURE_JELLYFISH, EntityType.Builder.of(NatureJellyfishEntity::new, MobCategory.WATER_AMBIENT).sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<VoidJellyfishEntity>> VOID_JELLYFISH = IcariaEntityTypes.register(IcariaEntityTypeIds.VOID_JELLYFISH, EntityType.Builder.of(VoidJellyfishEntity::new, MobCategory.WATER_AMBIENT).sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<WaterJellyfishEntity>> WATER_JELLYFISH = IcariaEntityTypes.register(IcariaEntityTypeIds.WATER_JELLYFISH, EntityType.Builder.of(WaterJellyfishEntity::new, MobCategory.WATER_AMBIENT).sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<LootVaseEntity>> LOOT_VASE = IcariaEntityTypes.register(IcariaEntityTypeIds.LOOT_VASE, EntityType.Builder.<LootVaseEntity>of(LootVaseEntity::new, MobCategory.MISC).sized(0.99F, 0.99F).clientTrackingRange(10).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<MyrmekeDroneEntity>> MYRMEKE_DRONE = IcariaEntityTypes.register(IcariaEntityTypeIds.MYRMEKE_DRONE, EntityType.Builder.of(MyrmekeDroneEntity::new, MobCategory.MONSTER).sized(0.99F, 0.49F).eyeHeight(0.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<MyrmekeSoldierEntity>> MYRMEKE_SOLDIER = IcariaEntityTypes.register(IcariaEntityTypeIds.MYRMEKE_SOLDIER, EntityType.Builder.of(MyrmekeSoldierEntity::new, MobCategory.MONSTER).sized(0.99F, 0.49F).eyeHeight(0.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<MyrmekeQueenEntity>> MYRMEKE_QUEEN = IcariaEntityTypes.register(IcariaEntityTypeIds.MYRMEKE_QUEEN, EntityType.Builder.of(MyrmekeQueenEntity::new, MobCategory.MONSTER).sized(0.99F, 0.49F).eyeHeight(0.249F));
	public static final DeferredHolder<EntityType<?>, EntityType<IcariaPaintingEntity>> PAINTING = IcariaEntityTypes.register(IcariaEntityTypeIds.PAINTING, EntityType.Builder.<IcariaPaintingEntity>of(IcariaPaintingEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(10).updateInterval(Integer.MAX_VALUE).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<CaptainRevenantEntity>> CAPTAIN_REVENANT = IcariaEntityTypes.register(IcariaEntityTypeIds.CAPTAIN_REVENANT, EntityType.Builder.of(CaptainRevenantEntity::new, MobCategory.MONSTER).sized(0.49F, 1.99F).eyeHeight(1.749F).fireImmune());
	public static final DeferredHolder<EntityType<?>, EntityType<CivilianRevenantEntity>> CIVILIAN_REVENANT = IcariaEntityTypes.register(IcariaEntityTypeIds.CIVILIAN_REVENANT, EntityType.Builder.of(CivilianRevenantEntity::new, MobCategory.MONSTER).sized(0.49F, 1.99F).eyeHeight(1.749F).fireImmune());
	public static final DeferredHolder<EntityType<?>, EntityType<CrawlerRevenantEntity>> CRAWLER_REVENANT = IcariaEntityTypes.register(IcariaEntityTypeIds.CRAWLER_REVENANT, EntityType.Builder.of(CrawlerRevenantEntity::new, MobCategory.MONSTER).sized(0.49F, 0.749F).eyeHeight(0.3749F).fireImmune());
	public static final DeferredHolder<EntityType<?>, EntityType<OvergrownRevenantEntity>> OVERGROWN_REVENANT = IcariaEntityTypes.register(IcariaEntityTypeIds.OVERGROWN_REVENANT, EntityType.Builder.of(OvergrownRevenantEntity::new, MobCategory.MONSTER).sized(0.49F, 1.99F).eyeHeight(1.749F).fireImmune());
	public static final DeferredHolder<EntityType<?>, EntityType<PyromancerRevenantEntity>> PYROMANCER_REVENANT = IcariaEntityTypes.register(IcariaEntityTypeIds.PYROMANCER_REVENANT, EntityType.Builder.of(PyromancerRevenantEntity::new, MobCategory.MONSTER).sized(0.49F, 1.99F).eyeHeight(1.749F).fireImmune());
	public static final DeferredHolder<EntityType<?>, EntityType<NetherPyromancerRevenantEntity>> NETHER_PYROMANCER_REVENANT = IcariaEntityTypes.register(IcariaEntityTypeIds.NETHER_PYROMANCER_REVENANT, EntityType.Builder.of(NetherPyromancerRevenantEntity::new, MobCategory.MONSTER).sized(0.49F, 1.99F).eyeHeight(1.749F).fireImmune());
	public static final DeferredHolder<EntityType<?>, EntityType<SoldierRevenantEntity>> SOLDIER_REVENANT = IcariaEntityTypes.register(IcariaEntityTypeIds.SOLDIER_REVENANT, EntityType.Builder.of(SoldierRevenantEntity::new, MobCategory.MONSTER).sized(0.49F, 1.99F).eyeHeight(1.749F).fireImmune());
	public static final DeferredHolder<EntityType<?>, EntityType<RugEntity>> RUG = IcariaEntityTypes.register(IcariaEntityTypeIds.RUG, EntityType.Builder.<RugEntity>of(RugEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(10).updateInterval(Integer.MAX_VALUE).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<ScorpionEntity>> SCORPION = IcariaEntityTypes.register(IcariaEntityTypeIds.SCORPION, EntityType.Builder.of(ScorpionEntity::new, MobCategory.MONSTER).sized(1.49F, 0.99F).eyeHeight(0.749F));
	public static final DeferredHolder<EntityType<?>, EntityType<SlugEntity>> CLUSTER_SLUG = IcariaEntityTypes.register(IcariaEntityTypeIds.CLUSTER_SLUG, EntityType.Builder.of(SlugEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<SnullEntity>> FOREST_SNULL = IcariaEntityTypes.register(IcariaEntityTypeIds.FOREST_SNULL, EntityType.Builder.of(SnullEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<SnullEntity>> SNULL = IcariaEntityTypes.register(IcariaEntityTypeIds.SNULL, EntityType.Builder.of(SnullEntity::new, MobCategory.MONSTER).sized(0.99F, 0.99F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<SolifugaeEntity>> SOLIFUGAE = IcariaEntityTypes.register(IcariaEntityTypeIds.SOLIFUGAE, EntityType.Builder.of(SolifugaeEntity::new, MobCategory.MONSTER).sized(0.99F, 0.49F).eyeHeight(0.49F));
	public static final DeferredHolder<EntityType<?>, EntityType<AntiGravitySpellEntity>> ANTI_GRAVITY_SPELL = IcariaEntityTypes.register(IcariaEntityTypeIds.ANTI_GRAVITY_SPELL, EntityType.Builder.of(AntiGravitySpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<FortifyingSpellEntity>> FORTIFYING_SPELL = IcariaEntityTypes.register(IcariaEntityTypeIds.FORTIFYING_SPELL, EntityType.Builder.of(FortifyingSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<HealingSpellEntity>> HEALING_SPELL = IcariaEntityTypes.register(IcariaEntityTypeIds.HEALING_SPELL, EntityType.Builder.of(HealingSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<BubbleSpellEntity>> BUBBLE_SPELL = IcariaEntityTypes.register(IcariaEntityTypeIds.BUBBLE_SPELL, EntityType.Builder.of(BubbleSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<FreezingSpellEntity>> FREEZING_SPELL = IcariaEntityTypes.register(IcariaEntityTypeIds.FREEZING_SPELL, EntityType.Builder.of(FreezingSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<MagicMissileSpellEntity>> MAGIC_MISSILE_SPELL = IcariaEntityTypes.register(IcariaEntityTypeIds.MAGIC_MISSILE_SPELL, EntityType.Builder.of(MagicMissileSpellEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<StoolEntity>> STOOL = IcariaEntityTypes.register(IcariaEntityTypeIds.STOOL, EntityType.Builder.of(StoolEntity::new, MobCategory.MISC).sized(0.749F, 0.749F).eyeHeight(0.3749F).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<ThogEntity>> THOG = IcariaEntityTypes.register(IcariaEntityTypeIds.THOG, EntityType.Builder.of(ThogEntity::new, MobCategory.CREATURE).sized(0.749F, 0.99F).eyeHeight(0.749F));
	public static final DeferredHolder<EntityType<?>, EntityType<VinegarEntity>> VINEGAR = IcariaEntityTypes.register(IcariaEntityTypeIds.VINEGAR, EntityType.Builder.<VinegarEntity>of(VinegarEntity::new, MobCategory.MISC).sized(0.49F, 0.49F).clientTrackingRange(4).updateInterval(20).noLootTable());
	public static final DeferredHolder<EntityType<?>, EntityType<VinegaroonEntity>> VINEGAROON = IcariaEntityTypes.register(IcariaEntityTypeIds.VINEGAROON, EntityType.Builder.of(VinegaroonEntity::new, MobCategory.MONSTER).sized(1.49F, 0.749F).eyeHeight(0.749F));

	public static <T extends Entity> DeferredHolder<EntityType<?>, EntityType<T>> register(ResourceKey<EntityType<?>> pResourceKey, EntityType.Builder<T> pBuilder) {
		return IcariaEntityTypes.ENTITY_TYPES.register(pResourceKey.identifier().getPath(), () -> pBuilder.build(pResourceKey));
	}
}
