package com.axanthic.landsoficaria.common.registry;

import com.axanthic.landsoficaria.common.blocks.*;
import com.axanthic.landsoficaria.common.blocks.MossBlock;
import com.axanthic.landsoficaria.LandsOfIcariaInfo;
import com.axanthic.landsoficaria.client.LandsOfIcariaTabs;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.Material;
import net.minecraft.world.level.material.MaterialColor;

import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Function;
import java.util.function.Supplier;

public class LandsOfIcariaBlocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, LandsOfIcariaInfo.MODID);
    public static final DeferredRegister<Item> ITEMS = LandsOfIcariaItems.ITEMS;

    public static final RegistryObject<Block> MARL_GRASS = register("marl_grass", () -> new MarlGrassBlock(BlockBehaviour.Properties.of(Material.GRASS, MaterialColor.COLOR_GREEN).sound(SoundType.GRASS).explosionResistance(0.6F).strength(0.6F).randomTicks()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> MARL = register("marl", () -> new MarlBlock(BlockBehaviour.Properties.of(Material.DIRT, MaterialColor.COLOR_BROWN).sound(SoundType.GRAVEL).explosionResistance(0.5F).strength(0.5F)), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> MARL_COARSE = register("marl_coarse", () -> new MarlCoarseBlock(BlockBehaviour.Properties.of(Material.DIRT, MaterialColor.COLOR_BROWN).sound(SoundType.GRAVEL).explosionResistance(0.5F).strength(0.5F)), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> FARMLAND = register("farmland", () -> new FarmlandBlock(BlockBehaviour.Properties.of(Material.DIRT, MaterialColor.COLOR_BROWN).sound(SoundType.GRAVEL).explosionResistance(0.6F).strength(0.6F).randomTicks()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> FARMLAND_FERTILIZED = register("farmland_fertilized", () -> new FarmlandFertilizedBlock(BlockBehaviour.Properties.of(Material.DIRT, MaterialColor.COLOR_BROWN).sound(SoundType.GRAVEL).explosionResistance(0.6F).strength(0.6F).randomTicks()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> LOAM = register("loam", () -> new LoamBlock(BlockBehaviour.Properties.of(Material.DIRT, MaterialColor.TERRACOTTA_LIGHT_GRAY).sound(SoundType.GRAVEL).explosionResistance(0.6F).strength(0.6F)), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> MOSS_0 = register("moss_0", () -> new MossBlock(BlockBehaviour.Properties.of(Material.MOSS, MaterialColor.COLOR_GREEN).sound(SoundType.MOSS).explosionResistance(0.15F).strength(0.15F)), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeFlora)));
    public static final RegistryObject<Block> MOSS_1 = register("moss_1", () -> new MossBlock(BlockBehaviour.Properties.of(Material.MOSS, MaterialColor.COLOR_GREEN).sound(SoundType.MOSS).explosionResistance(0.15F).strength(0.15F)), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeFlora)));
    public static final RegistryObject<Block> MOSS_2 = register("moss_2", () -> new MossBlock(BlockBehaviour.Properties.of(Material.MOSS, MaterialColor.COLOR_GREEN).sound(SoundType.MOSS).explosionResistance(0.15F).strength(0.15F)), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeFlora)));
    public static final RegistryObject<Block> LOAM_BRICKS = register("loam_bricks", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_PINK).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> LOAM_BRICKS_SLAB = register("loam_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(LOAM_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> LOAM_BRICKS_STAIRS = register("loam_bricks_stairs", () -> new StairBlock(LOAM_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(LOAM_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> LOAM_BRICKS_WALL = register("loam_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(LOAM_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_ADOBE = register("yellowstone_adobe", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_ADOBE_SLAB = register("yellowstone_adobe_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(YELLOWSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_ADOBE_STAIRS = register("yellowstone_adobe_stairs", () -> new StairBlock(YELLOWSTONE_ADOBE.get().defaultBlockState(), BlockBehaviour.Properties.copy(YELLOWSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_ADOBE_WALL = register("yellowstone_adobe_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(YELLOWSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_COBBLE = register("yellowstone_cobble", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_COBBLE_SLAB = register("yellowstone_cobble_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(YELLOWSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_COBBLE_STAIRS = register("yellowstone_cobble_stairs", () -> new StairBlock(YELLOWSTONE_COBBLE.get().defaultBlockState(), BlockBehaviour.Properties.copy(YELLOWSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_COBBLE_WALL = register("yellowstone_cobble_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(YELLOWSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE = register("yellowstone", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_SLAB = register("yellowstone_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(YELLOWSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_STAIRS = register("yellowstone_stairs", () -> new StairBlock(YELLOWSTONE.get().defaultBlockState(), BlockBehaviour.Properties.copy(YELLOWSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_WALL = register("yellowstone_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(YELLOWSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_BRICKS = register("yellowstone_bricks", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_BRICKS_SLAB = register("yellowstone_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(YELLOWSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_BRICKS_STAIRS = register("yellowstone_bricks_stairs", () -> new StairBlock(YELLOWSTONE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(YELLOWSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_BRICKS_WALL = register("yellowstone_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(YELLOWSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> YELLOWSTONE_CHISELED = register("yellowstone_chiseled", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_ADOBE = register("silkstone_adobe", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_PINK).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_ADOBE_SLAB = register("silkstone_adobe_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SILKSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_ADOBE_STAIRS = register("silkstone_adobe_stairs", () -> new StairBlock(SILKSTONE_ADOBE.get().defaultBlockState(), BlockBehaviour.Properties.copy(SILKSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_ADOBE_WALL = register("silkstone_adobe_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SILKSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_COBBLE = register("silkstone_cobble", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_PINK).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_COBBLE_SLAB = register("silkstone_cobble_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SILKSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_COBBLE_STAIRS = register("silkstone_cobble_stairs", () -> new StairBlock(SILKSTONE_COBBLE.get().defaultBlockState(), BlockBehaviour.Properties.copy(SILKSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_COBBLE_WALL = register("silkstone_cobble_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SILKSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE = register("silkstone", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_PINK).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_SLAB = register("silkstone_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SILKSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_STAIRS = register("silkstone_stairs", () -> new StairBlock(SILKSTONE.get().defaultBlockState(), BlockBehaviour.Properties.copy(SILKSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_WALL = register("silkstone_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SILKSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_BRICKS = register("silkstone_bricks", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_PINK).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_BRICKS_SLAB = register("silkstone_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SILKSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_BRICKS_STAIRS = register("silkstone_bricks_stairs", () -> new StairBlock(SILKSTONE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(SILKSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_BRICKS_WALL = register("silkstone_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SILKSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SILKSTONE_CHISELED = register("silkstone_chiseled", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_PINK).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_ADOBE = register("sunstone_adobe", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_ADOBE_SLAB = register("sunstone_adobe_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SUNSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_ADOBE_STAIRS = register("sunstone_adobe_stairs", () -> new StairBlock(SUNSTONE_ADOBE.get().defaultBlockState(), BlockBehaviour.Properties.copy(SUNSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_ADOBE_WALL = register("sunstone_adobe_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SUNSTONE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_COBBLE = register("sunstone_cobble", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_COBBLE_SLAB = register("sunstone_cobble_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SUNSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_COBBLE_STAIRS = register("sunstone_cobble_stairs", () -> new StairBlock(SUNSTONE_COBBLE.get().defaultBlockState(), BlockBehaviour.Properties.copy(SUNSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_COBBLE_WALL = register("sunstone_cobble_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SUNSTONE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE = register("sunstone", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_SLAB = register("sunstone_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SUNSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_STAIRS = register("sunstone_stairs", () -> new StairBlock(SUNSTONE.get().defaultBlockState(), BlockBehaviour.Properties.copy(SUNSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_WALL = register("sunstone_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SUNSTONE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_BRICKS = register("sunstone_bricks", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_BRICKS_SLAB = register("sunstone_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(SUNSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_BRICKS_STAIRS = register("sunstone_bricks_stairs", () -> new StairBlock(SUNSTONE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(SUNSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_BRICKS_WALL = register("sunstone_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(SUNSTONE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> SUNSTONE_CHISELED = register("sunstone_chiseled", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.WOOD).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_ADOBE = register("voidshale_adobe", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.COLOR_GRAY).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_ADOBE_SLAB = register("voidshale_adobe_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(VOIDSHALE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_ADOBE_STAIRS = register("voidshale_adobe_stairs", () -> new StairBlock(VOIDSHALE_ADOBE.get().defaultBlockState(), BlockBehaviour.Properties.copy(VOIDSHALE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_ADOBE_WALL = register("voidshale_adobe_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(VOIDSHALE_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_COBBLE = register("voidshale_cobble", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.COLOR_GRAY).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_COBBLE_SLAB = register("voidshale_cobble_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(VOIDSHALE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_COBBLE_STAIRS = register("voidshale_cobble_stairs", () -> new StairBlock(VOIDSHALE_COBBLE.get().defaultBlockState(), BlockBehaviour.Properties.copy(VOIDSHALE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_COBBLE_WALL = register("voidshale_cobble_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(VOIDSHALE_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE = register("voidshale", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.COLOR_GRAY).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_SLAB = register("voidshale_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(VOIDSHALE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_STAIRS = register("voidshale_stairs", () -> new StairBlock(VOIDSHALE.get().defaultBlockState(), BlockBehaviour.Properties.copy(VOIDSHALE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_WALL = register("voidshale_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(VOIDSHALE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_BRICKS = register("voidshale_bricks", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.COLOR_GRAY).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_BRICKS_SLAB = register("voidshale_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(VOIDSHALE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_BRICKS_STAIRS = register("voidshale_bricks_stairs", () -> new StairBlock(VOIDSHALE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(VOIDSHALE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_BRICKS_WALL = register("voidshale_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(VOIDSHALE_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> VOIDSHALE_CHISELED = register("voidshale_chiseled", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.COLOR_GRAY).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_ADOBE = register("baetyl_adobe", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_CYAN).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_ADOBE_SLAB = register("baetyl_adobe_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(BAETYL_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_ADOBE_STAIRS = register("baetyl_adobe_stairs", () -> new StairBlock(BAETYL_ADOBE.get().defaultBlockState(), BlockBehaviour.Properties.copy(BAETYL_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_ADOBE_WALL = register("baetyl_adobe_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(BAETYL_ADOBE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_COBBLE = register("baetyl_cobble", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_CYAN).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_COBBLE_SLAB = register("baetyl_cobble_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(BAETYL_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_COBBLE_STAIRS = register("baetyl_cobble_stairs", () -> new StairBlock(BAETYL_COBBLE.get().defaultBlockState(), BlockBehaviour.Properties.copy(BAETYL_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_COBBLE_WALL = register("baetyl_cobble_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(BAETYL_COBBLE.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL = register("baetyl", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_CYAN).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_SLAB = register("baetyl_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(BAETYL.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_STAIRS = register("baetyl_stairs", () -> new StairBlock(BAETYL.get().defaultBlockState(), BlockBehaviour.Properties.copy(BAETYL.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_WALL = register("baetyl_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(BAETYL.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_BRICKS = register("baetyl_bricks", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_CYAN).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_BRICKS_SLAB = register("baetyl_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(BAETYL_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_BRICKS_STAIRS = register("baetyl_bricks_stairs", () -> new StairBlock(BAETYL_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(BAETYL_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_BRICKS_WALL = register("baetyl_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(BAETYL_BRICKS.get())), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));
    public static final RegistryObject<Block> BAETYL_CHISELED = register("baetyl_chiseled", () -> new Block(BlockBehaviour.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_CYAN).sound(SoundType.STONE).explosionResistance(6.0F).strength(1.5F).requiresCorrectToolForDrops()), object -> () -> new BlockItem(object.get(), new Item.Properties().tab(LandsOfIcariaTabs.creativeBlocks)));

    private static <T extends Block> RegistryObject<T> registerBlock(final String name, final Supplier<? extends T> block) {
        return BLOCKS.register(name, block);
    }

    private static <T extends Block> RegistryObject<T> register(final String name, final Supplier<? extends T> block, Function<RegistryObject<T>, Supplier<? extends Item>> item) {
        RegistryObject<T> object = registerBlock(name, block);
        ITEMS.register(name, item.apply(object));
        return object;
    }
}
